### ISSUE TITLE
Hide expired leases

### ISSUE THREAD

**Issue by mietzen** [jbaconsult/opnsense_stuff#3]
Hi! Tanks for this awesome widget! 

I don't no much about php but I've thought that we would only show static and active leases: 

```
if (($data['act'] == "active") || ($data['act'] == "static") || ($_GET['all'] == 1)) 
```

But my list show lots of expired leases:

![image](https://github.com/jbaconsult/opnsense_stuff/assets/31704359/03a0c0f8-6cd6-4e1e-a40c-2bb847e92a0d)

I'm running OPNsense 23.7

**Comment by jbaconsult** [comment]
Thank you for pointing out.Please feel free to create a pull request!

**Comment by mietzen** [comment]
It was more kind of a question if this is expected behaviour or not 😉

**Comment by mietzen** [comment]
Ok that was easy
